GET http://localhost:3003/api/blogs
###
GET http://localhost:3003/api

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Mobey PP",
  "author": "J. K. Rolling",
  "url": "localhost:2000",
  "likes": 10
}
